### ISSUE TITLE
test zabbix_maintenance unstable

### ISSUE THREAD

**Issue by gundalow** [ansible-collections/community.zabbix#118]
##### SUMMARY
The tests/integration/targets/test_zabbix_maintenance test sometimes fails, so has been marked disabled by updating 
`tests/integration/targets/test_zabbix_maintenance/aliases` in https://github.com/ansible-collections/community.zabbix/pull/110

##### ISSUE TYPE
- Bug Report

**Comment by D3DeFi** [comment]
This is due to `zabbix_maintenance` defining start time by itself via `datetime.now()`. So if we run module in the tests, then experience lag and run it one second later, `start_time` would be different by then and `zabbix_maintenance` will report `changed=True`.

Few options that come to my mind:

- we declare in the documentation that this modules is not to be used in idempotent way
- we provide module argument `start_time` for user to provide his custom starting time, that could have been generated via some fact or so

**Comment by D3DeFi** [comment]
#375 reintroduced tests for zabbix_maintenance
unfortunately, due to the nature of the module it will never be idempotent if run 2nd time in a row after a few seconds
