### ISSUE TITLE
[Discussion] Support of Zabbix Versions

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#171]
##### SUMMARY
How exactly is the stance which versions of zabbix to support?

![image](https://user-images.githubusercontent.com/453368/89501366-80ef9180-d7c3-11ea-963b-4288daadbd8d.png)

As this collection is now growing and growing and the tests are getting more complex I feel we should set a fixed scheme here.
IMO:
- Support of LTS releases over the timespan of "Full Support"... but not extended.
- Support of current non LTS release with removing last non LTS after some time ( 3/6 Months? )

Based on that we currently would do 4.0.x LTS, 4.4.x, 5.0.x LTS. Once 5.2.x releases shifting out 4.4.x after some months.
But dropping 3.0 LTS for now.

##### ISSUE TYPE
- Feature Idea

**Comment by D3DeFi** [comment]
Hmm, I am all up for shifting to full support instead of extended support. We would need to document that in README instead of linking to [zabbix docs](https://www.zabbix.com/life_cycle_and_release_policy).

"After some months" here would probably need to be breaking changes releases. So with incrementing major patch number to X.0.0 we can drop support for something. This of course can happen sooner in main/devel branches, but my logic behind it is that we should probably start cleaning our code as well.

And another topic, roles are following different support schematic, we would need to at least mention it in our life cycle and release policy.

This is maybe also a good time to merge this topic with #26 (after 1.0.0 release).

**Comment by D3DeFi** [comment]
Also 4.4.x we support anyways now, 5.2 we would probably too since there will be some issues for sure. So why not include that as well, but this one without code cleanups. Since logic for < 4.4 would still benefit 4.0 in full support mode and so on

**Comment by rockaut** [comment]
You're right. I think most of this change would only be to ease the things for this project. And users willing to keep with an extended support release are most likely to also keep an static release of this one here too.

IMO 1.0.0 would be a good step for this. Given that it WILL still work for older Zabbix Versions as we haven't changed something, shifting to the collection might be a good breaking point.

**Comment by D3DeFi** [comment]
Just to confirm I understand you correctly @rockaut:

Announce changes in the supported version (from extended to full, 3.0 drop) with 1.0.0 and then aim for dropping them in 1.1.0, etc..?

**Comment by rockaut** [comment]
Hmm... no, dropping 3.0 with 1.0.0.
I can see that this is aggressive and might not fit good. But I don't think dropping 3.0 will hurt many ... which are also migrating to Ansible 2.10 and 1.0.0 !

Also dropping anything would need a major imo so 1.1.0 wouldn't fit.

**Comment by D3DeFi** [comment]
@sky-joker what do you think?

@rockaut but we cannot drop 3.0 without changing our focus from extended support to full support as 3.0 is still in the extended support period.

**Comment by sky-joker** [comment]
There are only a few more days before v1.0.0 is released.  
We have not officially announced that we will no longer support Zabbix 3.0 as of v1.0.0.  
I think we need to be notified in advance of which version you will no longer support.  
So I think it will be after v1.0.0 that we drop support for 3.0.(May be v1.x.x)  
It can't be helped this time because there is no time until the release deadline, but we need to decide in advance which version we will not support from next time.

> That means 1.0.0 will be the first release that will officially no longer support 3.0 (on paper, but it will still support it since we are not changing code in anyway yet. Who knows, maybe we will accidentaly break 3.0 support with 1.0.1, but since we no longer guarantee it, then it should be ok)

Yes, the v1.0.0 code still has Zabbix 3.0 code and is supported.  
So I think that the unsupported Zabbix 3.0 should be after v1.0.0.  
I think the version that this module will no longer support for Zabbix 3.0 is v1.0.0 or later.

**Comment by D3DeFi** [comment]
Yes, this would feel extremly pushed. What we can do is announce that changes are gonna happen to zabbix supported versions.

But this too requires some time to document and think about, which I do not have in regards to other tasks that are required before 1.0.0.

So lets agree on some gitter session after the release where we address this and release policy for the collection as well.

**Comment by sky-joker** [comment]
> So lets agree on some gitter session after the release where we address this and release policy for the collection as well.

I agree :)

**Comment by rockaut** [comment]
Virtual Beeeeeeeeer 🍻

**Comment by D3DeFi** [comment]
With #231 now addressing #26, we should also look at this. I am up for switching from end of limited support to end of full support.

We can do this change in our README.md in section _supported Zabbix versions_. What stays open, however, is the question how we gonna approach zabbix 3.0 deprecation

**Comment by rockaut** [comment]
Yes definitely bumping to 2.x then.
