### ISSUE TITLE
Make user_medias optional/override

### ISSUE THREAD

**Issue by elrondvega** [ansible-collections/community.zabbix#261]
##### SUMMARY

Currently with the way user_medias works it overrides anything the end-user may have manually configured, even when user_medias isn't set, its defaulting to an empty array which is removing any configuration the user may have done manually. Per the API documentation the user_medias field is optional.

Don't update the user_medias when not set and/or provide an override setting like passwd has.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_user

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by sky-joker** [comment]
Thank you @elrondvega for the feature idea.

The zabbix_user module isn’t currently an assumption of manual operation.  
Because the configuration management and operation and playbook implement complex if assuming that allowing manual operation.  
So if automation does, the configuration management ideal considering should use CMDB or YAML.  
By managing the configuration in YAML with GitLab or GitHub, change history is automatically recorded and the latest settings can be found in YAML.  
In this way, there will be no difference in the configuration between the real machine and YAML.  
This is the best way to do it, assuming an automated operation.

But, I understand your feeling.  
If everyone wants this feature, I will consider implementing it.  
I just need to keep an eye on this for a while.

**Comment by elrondvega** [comment]
> The zabbix_user module isn’t currently an assumption of manual operation.

Sorry maybe I need to clarify, the module shouldn't assume just because something isn't set that it should be erased. 

> In this way, there will be no difference in the configuration between the real machine and YAML.

Ansible should only manage and configure the things it has been configured to manage, it shouldn't assume just because something isn't set/configured, that is should just remove those settings.

**Comment by sky-joker** [comment]
> This closely relates to what I have been observing with zabbix_host and other modules. Instead of defaulting to empty iterable that is not even required by Zabbix API we should default to None. 

Unfortunately, an error occurred that I tried after I change the user_media default value from list to None.  
(I'm sorry if I don't understand correctly.)  
The user_medias seems necessary to be the list(array) type.

https://www.zabbix.com/documentation/5.0/manual/api/reference/user/create

If implementation of this request feature to the module, it needs to get the existing user_media configures from Zabbix Server and include the configures to [request_data](https://github.com/ansible-collections/community.zabbix/blob/09660a8e18fa77639c018bc2f68fff139ac56bc1/plugins/modules/zabbix_user.py#L487) when updating a Zabbix user.

**Comment by elrondvega** [comment]
I was able to implement this change without querying the current state as the field is optional. I will submit a pull request.

**Comment by D3DeFi** [comment]
> I was able to implement this change without querying the current state as the field is optional. I will submit a pull request. 

Exactly. I meant my previous comment for all options that are not required. We should default those to None and then remove every None from the request data before sending create/update API calls

**Comment by sky-joker** [comment]
I see, That's what you mean.
I get it.
