### ISSUE TITLE
Module zabbix_action does not contain "Notify all involved"

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#29]
_From @lokly on 4 Jul 2019_

##### SUMMARY
The module zabbix_action does not contain the Zabbix operation "Notify all involved", that can be selected in the section "Recovery operations" and "Update operations".

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
lib/ansible/modules/monitoring/zabbix/zabbix_action.py

##### ANSIBLE VERSION
2.8.1

_Copied from original issue: https://github.com/ansible/ansible/issues/58719_

**Comment by D3DeFi** [comment]
@rubentsirunyan [commented](https://github.com/ansible/ansible/issues/58719#issuecomment-517645205):
> 
> 
> Hi @lokly. Both acknowledge and recovery operations have a `notify_all_involved` option.
> 
> https://github.com/ansible/ansible/blob/b8473276455cbeb49629b502f1f163be0c7eb45a/lib/ansible/modules/monitoring/zabbix/zabbix_action.py#L1219-L1249
> 
> The problem is that it is not stated in the documentation.

I've [stated](https://github.com/ansible/ansible/issues/58719#issuecomment-518262756) that it is not documented because of the huge sub-options documentation for `operations` is reused for both `recovery_operations` and `acknowledge_operations` as well. However, `operations` do not support `notify_all_involved`, thus the documentation entry is missing.

**Comment by D3DeFi** [comment]
The documentation fix is kinda ugly, but module options are so complex that it is probably better to have it at least this way that not at all.
