### ISSUE TITLE
Module zabbix_action maintenance_status requires unavailable operator

### ISSUE THREAD

**Issue by sky-joker** [ansible-collections/community.zabbix#30]
_From @sawicchiraw on 5 Jul 2019_

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
zabbix_action

##### ANSIBLE VERSION
```paste below
ansible 2.8.2
  config file = None
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.5/dist-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.5.2 (default, Nov 12 2018, 13:43:14) [GCC 5.4.0 20160609]
```

##### CONFIGURATION
```paste below
        conditions:
          - type: 'maintenance_status'
            operator: 'No'
            value: ''
            formulaid: A
```

##### OS / ENVIRONMENT
Linux zabbix 4.4.0-154-generic [#181](https://github.com/ansible/ansible/pull/181)-Ubuntu SMP Tue Jun 25 05:29:03 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

##### STEPS TO REPRODUCE
zabbix 4.0, zabbix api Action object
https://www.zabbix.com/documentation/4.0/manual/api/reference/action/object
When Action operation-conditiontype is 16 - problem is suppressed, it requires new operator "10 - Yes; or 11 - No. "

lib/python3.5/dist-packages/ansible/modules/monitoring/zabbix/zabbix_action.py
line 1391~
try:
return to_numeric_value([
"=",
"<>",
"like",
"not like",
"in",
">=",
"<=",
"not in",
"dammy 8",
"dammy 9",
"Yes",
"No"], _condition['operator']
)

then I can add zabbix action with maintenance_status

##### ACTUAL RESULTS

```paste below

```

_Copied from original issue: https://github.com/ansible/ansible/issues/58747_

**Comment by D3DeFi** [comment]
Slipped our attention back when zabbix modules were part of the upstream repo. This issue was addressed in ansible/ansible#58379

Only difference is that before Zabbix 3.4 condition type 16 was `Maintenance status` and required `in` and `not in` operators. Since Zabbix 4.0 condition type 16 is now called `Problem is suppressed` and requires operators `Yes` and `No`. Luckily, all of them are supported as of now.

I've highlighted this difference in #43.
