### ISSUE TITLE
zabbix_web php-fpm restart is failing with zabbix >= 5.0

### ISSUE THREAD

**Issue by FloMeyer** [ansible-collections/community.zabbix#308]
##### SUMMARY
execution is failing at restarting php-fpm with php7.4-fpm because there is no service php-fpm.

Code from community/zabbix/roles/zabbix_web/handlers/main.yml:

**- name: restart php-fpm
  service:
    name: "{{ 'rh-php72-php-fpm' if zabbix_php_fpm else 'php-fpm' }}"
    state: restarted
    enabled: yes
  become: yes
  when:
    - zabbix_version is version('5.0', '>=')**

- name: restart php-fpm-version
  service:
    name: php{{ zabbix_php_version }}-fpm
    state: restarted
    enabled: yes
  become: yes
  when:
    - zabbix_version is version('5.0', '>=')

with php7.4-fpm i only need the next part "restart php-fpm-version" but not "restart php-fpm".

##### ISSUE TYPE
- Bug Report

##### ANSIBLE VERSION

```paste below
I'm running AWX 16.0.0
ansible 2.9.15

```

##### CONFIGURATION

```paste below

```

##### OS / ENVIRONMENT / Zabbix Version

Ubuntu 20
python version = 3.6.8 (default, Aug 24 2020, 17:57:11) [GCC 8.3.1 20191121 (Red Hat 8.3.1-5)]

##### STEPS TO REPRODUCE

```yaml

```

##### ACTUAL RESULTS

```paste below
RUNNING HANDLER [community.zabbix.zabbix_web : restart php-fpm] ****************
task path: /tmp/awx_394_tj2ea0yw/project/collections/ansible_collections/community/zabbix/roles/zabbix_web/handlers/main.yml:31

{
  "msg": "Could not find the requested service php-fpm: host",
  "invocation": {
    "module_args": {
      "name": "php-fpm",
      "state": "restarted",
      "enabled": true,
      "daemon_reload": false,
      "daemon_reexec": false,
      "no_block": false,
      "force": null,
      "masked": null,
      "user": null,
      "scope": null
    }
  },
  "_ansible_no_log": false,
  "changed": false
}

```

**Comment by brunoscota** [comment]
same happened to me. Adding: 

`- role: geerlingguy.apache-php-fpm`

worked nice for me!

**Comment by dj-wasabi** [comment]
Hi @FloMeyer 

You do have php-fpm installed? What role did you use?

**Comment by FloMeyer** [comment]
Sorry, i forgot to post my playbook.
I am using the roles geerlingguy.php and geerlingguy.apache-php-fpm.

My Playbook looks like this:
- hosts: all
  become: yes

  vars:
    php_enable_php_fpm: true
    apache_vhosts:
      - servername: "hostname.lan"
        documentroot: "/var/www/html"
        extra_parameters: |
              ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000/var/www/html"

  roles:
    - role: geerlingguy.apache
    - role: geerlingguy.mysql
      become: yes
    - geerlingguy.php
    - geerlingguy.apache-php-fpm
    - role: community.zabbix.zabbix_server
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbport: 3306
    - role: community.zabbix.zabbix_web
      zabbix_url: zabbix.medi.local
      zabbix_server_database: mysql
      zabbix_server_database_long: mysql
      zabbix_server_dbport: 3306

**Comment by dj-wasabi** [comment]
Hi @FloMeyer 

And you use CentOS8 right?
I will try to replicate it, as I had issues with PHP-FPM all the time.

**Comment by FloMeyer** [comment]
> Hi @FloMeyer
> 
> And you use CentOS8 right?
> I will try to replicate it, as I had issues with PHP-FPM all the time.

I am Using Ubuntu 20.04. I commented out the first part and now it runs fine.. so with just the "restart php-fpm-version" part its fine.

**Comment by dj-wasabi** [comment]
Hi @FloMeyer 

I have tried to replicate it, see in branch https://github.com/dj-wasabi/community.zabbix/tree/reproduce-308
But it seems to work fine in the Molecule Ubuntu 20.04 image. I am not sure yet on how to proceed.

Kind regards,
Werner

**Comment by sangdrax8** [comment]
I am seeing this same issue with my Ubuntu 20.04, and looking at the handlers I don't see how they even could ever work?

`- name: restart php-fpm
  service:
    name: "{{ 'rh-php72-php-fpm' if zabbix_php_fpm else 'php-fpm' }}"
    state: restarted
    enabled: yes
  become: yes
  when:
    - zabbix_version is version('5.0', '>=')

- name: restart php-fpm-version
  service:
    name: php{{ zabbix_php_version }}-fpm
    state: restarted
    enabled: yes
  become: yes
  when:
    - zabbix_version is version('5.0', '>=')`
    
    This handler when condition for 5.0 or greater will cause BOTH of these to always try and run.  I don't see how it could not always fail when the handler is called (perhaps it succeeds if you never call this handler?)

In the Ubuntu case I am using, mine is php74-fpm, so as stated in this bug report, I only need the "restart php-fpm-versoin" to run.  However the first one matches and then fails because there isn't a service called php-fpm.  There aren't a set of variables I can find to fix this.

**Comment by Droncz** [comment]
Hello,
I think I've run basically into the same problem, and I FOUND A SOLUTION:

I am using the role "geerlingguy.php", followed by a "community.zabbix.zabbix_web" role on Ubuntu 18.04, and it was failing on calling the handler "restart php-fpm" with an error because of non-existent service.

The problem lies in fact, that both roles define the handler of the name: "restart php-fpm":
 * geerlingguy.php : in file "roles/geerlingguy.php/handlers/main.yml"
 * zabbix_web : in file "collections/ansible_collections/community/zabbix/roles/zabbix_web/handlers/main.yml"

The "geerlingguy.php" role is calling (restarting) the correct name of the service regardless of Debian/Redhat Linux flavour (Debian/Ubuntu uses php service name with a version - for example "php7.4-fpm").
The "zabbix_web" has this handler meant only for RedHat flavour (it does not use the version in the name), and for Debian flavour, it uses handler "restart php-fpm-version".
The problem arises in situations where the "geerlingguy.php" role notifies the handler "restart php-fpm". As the two roles are run in sequence, the handlers trigger at the end and calling for the handler "restart php-fpm" also triggers the same-name handler of "zabbix_web" role, which is meant for RedHat only, which - if run on Debian flavour - ends with the error mentioned.

My solution to this was to rename the handler of the "zabbix_web" role to "restart redhat-php-fpm" (together with modification of respective playbook). However, I don't think it is the most elegant solution on my end, so I suggest applying some similar renaming here - at the source.

Bye and best regards.

**Comment by dj-wasabi** [comment]
> Hello,
> I think I've run basically into the same problem, and I FOUND A SOLUTION:
> 
> I am using the role "geerlingguy.php", followed by a "community.zabbix.zabbix_web" role on Ubuntu 18.04, and it was failing on calling the handler "restart php-fpm" with an error because of non-existent service.
> 
> The problem lies in fact, that both roles define the handler of the name: "restart php-fpm":
> 
> * geerlingguy.php : in file "roles/geerlingguy.php/handlers/main.yml"
> * zabbix_web : in file "collections/ansible_collections/community/zabbix/roles/zabbix_web/handlers/main.yml"
> 
> The "geerlingguy.php" role is calling (restarting) the correct name of the service regardless of Debian/Redhat Linux flavour (Debian/Ubuntu uses php service name with a version - for example "php7.4-fpm").
> The "zabbix_web" has this handler meant only for RedHat flavour (it does not use the version in the name), and for Debian flavour, it uses handler "restart php-fpm-version".
> The problem arises in situations where the "geerlingguy.php" role notifies the handler "restart php-fpm". As the two roles are run in sequence, the handlers trigger at the end and calling for the handler "restart php-fpm" also triggers the same-name handler of "zabbix_web" role, which is meant for RedHat only, which - if run on Debian flavour - ends with the error mentioned.
> 
> My solution to this was to rename the handler of the "zabbix_web" role to "restart redhat-php-fpm" (together with modification of respective playbook). However, I don't think it is the most elegant solution on my end, so I suggest applying some similar renaming here - at the source.
> 
> Bye and best regards.

Hi @Droncz 
Thank you for your comment. Is there a way you can provide a PR for this? Unfortunately I don't have much time these days, so it would help if you are able to create a PR for this so you can immediately see that your solution helps (And that it is passing the CI as well). If not, hopefully someone else will able to help, otherwise I need to find some time for it.

Thanks in advance.
