### ISSUE TITLE
Allow disabling of mysql binary logging

### ISSUE THREAD

**Issue by derekpurdy** [ansible-collections/community.zabbix#365]
##### SUMMARY

Allow users to disable mysql binary logging if not required as it uses significant disk space.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_server role

##### ADDITIONAL INFORMATION

To disable binary logging, you can specify the --skip-log-bin or --disable-log-bin option at startup. If either of these options is specified and --log-bin is also specified, the option specified later takes precedence. 

https://dev.mysql.com/doc/refman/8.0/en/binary-log.html

```yaml

```

**Comment by dj-wasabi** [comment]
Hi @derekpurdy 

Can you explain in which part of the role it should be able to do something with disabling of MySQL binary logging? Because the roles for both the Server as the Proxy asumes that there is an MySQL instance already running before Zabbix Server and/or Proxy are installed.

Kind regards,
Werner

**Comment by derekpurdy** [comment]
Hello @dj-wasabi 

Sorry, I just realized that you configure the zabbix database but not install mysql directly. I will just take this off to a custom task to run before zabbix server installation.

Thanks
