### ISSUE TITLE
zabbix_user should not overwrite user defined settings 

### ISSUE THREAD

**Issue by weehal** [ansible-collections/community.zabbix#380]
##### SUMMARY
Every time when `zabbix_user`  task is called it overwrites user custom settings in zabbix - that makes them unusable. 

Don't update the user settings:
`lang, theme, refresh, rows_per_page, after_login_url`  etc. when differs from default or provide an override setting like passwd has.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
zabbix_user

##### ADDITIONAL INFORMATION
 it's similar to #261

**Comment by D3DeFi** [comment]
Thank you for opening this @weehal . Yes, this is definitely a bug since API doesn't require us to provide those values:
https://www.zabbix.com/documentation/current/manual/api/reference/user/object#user

So we should default them to `None` and don't send them via request if user doesn't specify them.

**Comment by sky-joker** [comment]
Thanks, @weehal for reporting the issue.  
I'll work on making a patch to resolve the issue.

**Comment by sky-joker** [comment]
@weehal
I made a patch to resolve this issue.  
So could you please look at https://github.com/ansible-collections/community.zabbix/pull/382?  

Unfortunately, there are some default values that I can't remove because backward compatibility will be broken.  
But, those will be removed in the future.
