### ISSUE TITLE
zabbix_host documentation regarding Zabbix user privileges

### ISSUE THREAD

**Issue by juresaht2** [ansible-collections/community.zabbix#548]
##### SUMMARY

It would be helpful if the [zabbix_host module](https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_host.py#L11) and [zabbix_host_info module documentation](https://github.com/ansible-collections/community.zabbix/blob/main/plugins/modules/zabbix_host_info.py#L21) indicated somewhere, that the errors "Hostgroup not found" and "Host not found" could indicate that the Zabbix-API user has insufficient privileges.

It would also be helpful if it was indicated that making the Zabbix-API user a Zabbix Super Admin, gives it privileges to view (and change) information used in typical operations, such as looking up existing host information or adding a host, without manually configuring access.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

zabbix_host module
zabbix_host_info module

##### ADDITIONAL INFORMATION

I found this fairly unintuitive. Perhaps the module error handling could be adjusted as well?

**Comment by dj-wasabi** [comment]
Hi @juresaht2 thank you for making time to create an issue. I disagree with you, as this is related to the Zabbix API and not specific with this collection. If you would use curl to create a host with the same information then you would get an error as well, as it is related to the user that you use with Zabbix. We just do some extra checking - like verifying the hostgroup exist - so we fail fast, instead of doing the actual request and might get errors. Also we can not say how you should setup Zabbix and what its requirements are for each and any case. Everyone has different needs, requirements and have different setups. We can not limit ourself to something, that is not the power of Ansible. Just like with any other collection/module, some basic understanding of the tool is required.

If we start with this, we eventually get a large document where everyone provides an issue (with a possible solution) that no one will read, or contains issues for something that actally the way is how the Zabbix API works.

How do you look at this @D3DeFi ?

**Comment by juresaht2** [comment]
Since you mentioned that only quick checking is done, it would be helpful to include a note that these errors might not mean what they say.

**Comment by D3DeFi** [comment]
I think this is not even specific to Zabbix API @dj-wasabi , but rather should be a knowledge of Zabbix Administrator him/herself - "I should not use user for Ansible that cannot read/write to objects I want to manage". I don't think this is anything we should be helping with at all. As was mentioned, we are providing tool that does a work for the user, but cannot think for themselves.

At this point I would even be scared just by simply changing errors, because some people may use them for something or catch them with `failed_when` statements in specific cases, so this would need to be properly deprecated. 

Although I am ok if you are willing to provide documentation PR that will add something like `make sure zabbix user used for ansible can read these groups` in `DOCUMENTATION` block of zabbix_host.
