### ISSUE TITLE
Test suite failling on HTTP timeouts

### ISSUE THREAD

**Issue by D3DeFi** [ansible-collections/community.zabbix#700]
##### SUMMARY

Sometimes our plugin integration tests are failing with:
```
TASK [test_zabbix_action : test - cleanup example template for zabbix_action module] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: zabbix_api.APITimeout: HTTP read timeout
fatal: [testhost]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1653382710.77-5541-160221198918365/AnsiballZ_zabbix_template.py\", line 143, in <module>\n    _ansiballz_main()\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1653382710.77-5541-160221198918365/AnsiballZ_zabbix_template.py\", line 135, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/runner/.ansible/tmp/ansible-tmp-1653382710.77-5541-160221198918365/AnsiballZ_zabbix_template.py\", line 81, in invoke_module\n    runpy.run_module(mod_name='ansible_collections.community.zabbix.plugins.modules.zabbix_template', init_globals=None, run_name='__main__', alter_sys=True)\n  File \"/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/runpy.py\", line 188, in run_module\n    fname, loader, pkg_name)\n  File \"/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/runpy.py\", line 82, in _run_module_code\n    mod_name, mod_fname, mod_loader, pkg_name)\n  File \"/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_zabbix_template_payload_RuEhMm/ansible_zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 795, in <module>\n  File \"/tmp/ansible_zabbix_template_payload_RuEhMm/ansible_zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 730, in main\n  File \"/tmp/ansible_zabbix_template_payload_RuEhMm/ansible_zabbix_template_payload.zip/ansible_collections/community/zabbix/plugins/modules/zabbix_template.py\", line 466, in delete_template\n  File \"/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/zabbix_api.py\", line 341, in method\n    return self.universal(\"%s.%s\" % (self.data[\"prefix\"], name), opts[0])\n  File \"/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/zabbix_api.py\", line 79, in wrapper\n    return self.do_request(self.json_obj(method, opts))['result']\n  File \"/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/zabbix_api.py\", line 348, in do_request\n    return self.parent.do_request(req)\n  File \"/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/site-packages/zabbix_api.py\", line 267, in do_request\n    raise APITimeout(\"HTTP read timeout\",)\nzabbix_api.APITimeout: HTTP read timeout\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```

Can be seen for example here (https://github.com/ansible-collections/community.zabbix/runs/6569619513?check_suite_focus=true) at the start. I suspect that this is some lag that Github Actions may show when heavily utilized?

How to best fix this? I am not sure that giving `retries:` to each task would be very nice solution.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
CI

**Comment by BGmot** [comment]
This issue is extremely weird, look at another failed test with the same error https://github.com/ansible-collections/community.zabbix/runs/6426759041?check_suite_focus=true at exactly the same place (plus there are identical runs).
Moreover look at re-runs with debug info, the run does not even reach this test, it fails at totally irrelevant:
https://github.com/ansible-collections/community.zabbix/runs/6569619513?check_suite_focus=true#step:7:4357
and exactly the same place in another test:
https://github.com/ansible-collections/community.zabbix/runs/6426759041?check_suite_focus=true#step:7:4361
```
"msg": "Template not found: ExampleTemplateForActionModule"
```
While this Template is really created:
https://github.com/ansible-collections/community.zabbix/runs/6569619513?check_suite_focus=true#step:7:52
And this confirms that the Template exists (changed=false):
https://github.com/ansible-collections/community.zabbix/runs/6569619513?check_suite_focus=true#step:7:1062

The same in another test:
https://github.com/ansible-collections/community.zabbix/runs/6426759041?check_suite_focus=true#step:7:52
https://github.com/ansible-collections/community.zabbix/runs/6426759041?check_suite_focus=true#step:7:1072

I am lost how it can happen.

**Comment by BGmot** [comment]
Surprisingly playing with local docker container I found out that deleting template does take several seconds to complete but only for the first time after container creation. I cannot explain this behaviour but changed timeout from default 10 seconds to 20, ran through github tests two times and they passed.

**Comment by D3DeFi** [comment]
Yeah, had something similar happening in the past also. I believe it was too related with github actions + zabbix_template. I was never able to reproduce this locally.

Anyway I think it is a good idea to increase timeout even further, it may tip rng luck on our side more consistently. Thanks for looking into this! :)
