### ISSUE TITLE
Standardize Tags in Roles

### ISSUE THREAD

**Issue by pyrodie18** [ansible-collections/community.zabbix#781]
##### SUMMARY
We don't seem to have a consistent standard for the use of tags within a role or across roles.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
All Roles

##### ADDITIONAL INFORMATION
In the server role, most, but not all tasks are tagged with `zabbix-server` even though the entire role itself is zabbix-server.  Other tags such as `database` are added into lots of related tasks, but not all.  Probably need to decide which tags we want to support and then standardize.

**Comment by evilhamsterman** [comment]
Also please don't use the `always` tag. If your role is used as part of a larger playbook with separate tags anything tagged `always` will always run even if not needed and often breaking other parts of the playbook. If a task is required for another task please add the same tag to both tasks.

**Comment by mathieumd** [comment]
You may want to look at how Debops assign tags (see for example [the role for Nginx](https://docs.debops.org/en/latest/ansible/roles/nginx/getting-started.html#ansible-tags)), with their naming: `role::zabbix_agent`, `role::zabbix_agent:config`, etc.

---

My use case is to only modify the Zabbix configuration (and then restart service), without running all other tasks.

I modified [`Configure zabbix-agent` task](https://github.com/ansible-collections/community.zabbix/blob/main/roles/zabbix_agent/tasks/Linux.yml#L112) to add the tag `role::zabbix_agent:config`. Now I can run configuration updates very fast:
```bash
ansible-playbook playbooks/monitoring.yml --diff -t role::zabbix_agent:config
```

**Comment by ggold7046** [comment]
Hi, I'm interested in doc contribution, if anyone can guide me I would love to work on this issue.

**Comment by D3DeFi** [comment]
> Hi, I'm interested in doc contribution, if anyone can guide me I would love to work on this issue.

@ggold7046 thank you for offering your help. When it comes to roles, documentation is not widely spread across this repo. Standard readme is present at docs/ for each role. (Also some very basic information is in root README.md)

Additionally, each role should have well documented variables in roles/*/defaults/* and that is pretty much it. 

That being said, I think this task would rather need reworking `tags: ` in each tasks/* file in each role, rather than changing documentation as the current tags are not systematic from what I read in this issue.
