### ISSUE TITLE
Refactor Version dependencies in modules/plugins

### ISSUE THREAD

**Issue by rockaut** [ansible-collections/community.zabbix#96]
I open this issues in advance to #92 . I would like to do one first small thing and refactor the way modules checks or acts on version dependency. Imo it's a good first and easy thing to contribute - I will open a PR and label it WIP.

##### SUMMARY
For example, from zabbix_host:

```python
self._zbx_api_version = zbx.api_version()[:5]
```

while zabbix_action does it this way:

```python
if float(self._zapi.api_version().rsplit('.', 1)[0]) >= 5.0:
```

Also there one plugin just requests the version everytime or in the `_init` while others pass it through an argument to functions.

##### ISSUE TYPE
- Feature Idea

**Comment by rockaut** [comment]
Also as answers the last comment there by @D3DeFi :

1. I think for contributors like me smaller refactors are also the way to go. It's easier to dip your toe in the code and get your head around how it works. Also I thinks it's the better way as a big overhaul would certainly introduce way more issues and problems as they might not get catched in tests at first place.

2. I personally don't like the idea of a `ZabbixBase` element. Let me explain why and read it just as my personal opinion: there already is such a thing with zabbix-api python module which is a hard dependency anyways. If there would be a ZabbixBase it would just make sense if the collection would drop zabbix-api after implementation. I guess you meant it that way? But zabbix-api is pretty good so I don't think it should be replaced. It would also again be another additional work on top of the already piling work? I know that there are some modules/plugins which do already wrap zabbix-api already again but also using it directly which is somehow confusing already.

Another negative thing on ZabbixBase is the portability imo: currently if something doesn't work as a user might want it, one can just take `zabbix_action.py` out of the collection, drop it into roles/myzabbix/library, modify it and is good to go. Infact that is the way I work around most bugs/things in collections and it's a life saver in production. (Of course after that it would be nice to contribute it (-; ). Now if it would depend on an ZabbixBase too this would be not as transparent, easy, or maybe even not possible at all.

**Comment by rockaut** [comment]
Would it be possible to an additional Label or Issue Type? Discussion would be a great thing currently as the collection is getting "bootstrapped".

**Comment by D3DeFi** [comment]
> 
> 
> Would it be possible to an additional Label or Issue Type? Discussion would be a great thing currently as the collection is getting "bootstrapped".

Label yes, issue types - I need to look if yes or no.

`ZabbixBase` - that was very distant and wild idea for me and only because I am seeing this pattern in other collections. For example [community.kubernetes/plugins/module_utils/common.py](https://github.com/ansible-collections/community.kubernetes/blob/master/plugins/module_utils/common.py). I haven't thought about it very much and I am aware that some people are probably benefiting from standalone design of the modules.

Just to be on the same page, not a replacement for `zabbix-api` - more like shared code for all of the modules. Something like:

```python
# this would contain parameters `server_url`, `login_user` and so on
from community.zabbix.module_utils.common import zabbix_argspec

# somewhere in main()
zabbix_argspec.update(module.params)
```

Maybe similar stuff for all of the classes. Lets say that wouldbe `ZabbixBase` would provide `self.zbx_version` or handle `atexit.register(zbx.logout)` for all of the modules. I would say this could be used as a natural enforcer to keep things consistent.

To be honest, I wanted to open such discussion after we stabilize bugs and 5.0 support. Not that I have time to play with something like this. But since we touched this subject, @sky-joker what is your opinion?

Only other alternative is to somehow force all modules to be consistent. Any other ideas?

**Comment by D3DeFi** [comment]
Back to the original question. If you are up for it, sure. Please iterate through the modules and ensure that `LooseVersion` is used consistently in each. Or have you had some other approach in mind?

**Comment by D3DeFi** [comment]
Waaaaaaaaaay better example than k8s is grafana:
https://github.com/ansible-collections/community.grafana/blob/master/plugins/module_utils/base.py

**Comment by sky-joker** [comment]
Essentially, I think `ZabbixBase` is necessary from the point of view of what it should be.
The parts that are standardized in other Collections are realized in `ZabbixBase`.
(I've always wanted to make a `Base(common.py like)` if I could find the time, but…, Other Collections to which I contribute are also making a `Base`)
But we can't have a `ZabbixBase` right away, so I think it's better to standardize version comparisons in `LooseVersion` first.
What to do with `ZabbixBase` needs further discussion.

**Comment by D3DeFi** [comment]
Definitively needs further discussion, but we have a lots of other things to worry about right now.

Lets go with minor changes first. Unifying version deps as @rockaut proposes is a promising way.
